name: Run PHP daily at 01:00 UTC

on:
  schedule:
    - cron: '0 1 * * *'    # setiap hari jam 01:00 UTC
  workflow_dispatch:

jobs:
  run-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run bot.php
        run: php bot.php
